### ISSUE TITLE
Need for disabling reactivity?

### ISSUE THREAD

**Issue by karlpokus** [mikowals/batch-insert#15]
Hi @mikowals 

Thanks for making this package. Just what I need. Just one question. Will a batch-insert amount to (1) a total of one DDP update message _or_ (2) as many DDP update messages as docs inserted into mongo?

I ask because if it's the latter I'd have to figure out a way to temporarily disable reactivity for connected clients or they'd probably crash.

/ Karl

**Comment by mikowals** [comment]
You can view the DDP messages to a client using the methods [here](http://richsilv.github.io/meteor/meteor-low-level-publications/) or [this package](https://github.com/rclai/meteor-ddp-inspector).

Client problems I have seen from too many DDP updates are usually when you are updating the DOM for many document changes in series rather than updating the DOM once after all changes have arrived.  I think the number of DDP messages received is irrelevant.

**Comment by karlpokus** [comment]
@mikowals

Thanks for the articles.

> I think the number of DDP messages received is irrelevant.

Sound like you know a way to render the DOM _after_ a specified amount of docs has been inserted. Is this possible?
