### ISSUE TITLE
will this bypass collection hooks ?

### ISSUE THREAD

**Issue by crapthings** [mikowals/batch-insert#26]
as title

https://github.com/matb33/meteor-collection-hooks

**Comment by mikowals** [comment]
I have never tried collection hooks with or without `batch-insert`.  My first step if problems arose when using both would be changing the order that the packages are added.  

Report back any results.  I am happy to consider pull requests if there is an improved way to add the `batchInsert` method so that it works better with other packages.

**Comment by WayneUong** [comment]
+1 this will be a great feature.
