### ISSUE TITLE
Auto fields from schema and after insert hooks not getting called after batch insert.

### ISSUE THREAD

**Issue by gauravraj** [mikowals/batch-insert#35]
I have used aldeed:collection2 to define schema for my Meteor collections. After calling batch insert on the collection, the createdAt field (auto field with Date.now() value) was null. Moreover, the after insert hook as also not called. Could you please let me know the reason for the issue and how can I resolve it?

**Comment by sergical** [comment]
Having the same issue

**Comment by evolross** [comment]
This is because under the hood this just uses `Collection.rawCollection()` to do a batch insert. That's not hooked into aldeed:collection2 or collection hooks. It's "out of reach" of Meteor.

The work-around is use batch-insert sparingly (only when you really need it). And then when using batch-insert, just make sure to initialize all values on the objects you're inserting and any triggered updates that your collection hooks would have picked up.

Another thing to think about is you probably don't want collection hooks firing on a batch insert anyway, that defeats the purpose of doing an efficient batch insert if your code then had to fire off a bunch of subsequent transactions per object that was inserted in the batch.  Probably better to just manually update things in the event of a batch insert.
