### ISSUE TITLE
ignore duplicates option?

### ISSUE THREAD

**Issue by jakobrosenberg** [mikowals/batch-insert#39]
Would it be possible to add an option to ignore duplicate inserts?

**Comment by mikowals** [comment]
I haven't thought about this code in a long time so my answer might be off base.  I think `batchInsert` mimics `insert` so it errors on duplicates.  If you want to ignore duplicates I think this is possible with `upsert`.

**Comment by mikowals** [comment]
My previous comment is not correct.  `upsert` can update multiple documents that match a query but it will only insert a single document if the search criteria aren't matched.  

Inserting multiple documents while ignoring duplicates is easy on the server by using `collection.rawCollection().insert([{_id: "1"}, {_id: "2"}], {ordered: false})`.

Ignoring database duplicates while maintaining Meteor's full stack reactivity and security would be great functionality but is much harder.  The point of this package is to wrap the easily accessed mongo driver methods to enable that full stack reactivity.  How could the client know the `_id`s of all documents being inserted?  Would `allow` and `deny` rules also need to be altered because a client `insert` might learn existing database items?

Closing for now.  If someone wants to propose a way to incorporate this I am happy to reopen and let that progress.
