### ISSUE TITLE
Feature request: batchUpsert

### ISSUE THREAD

**Issue by joegoldbeck** [mikowals/batch-insert#7]
Would be super helpful to also have batch upsert functionality. Should be doable. http://docs.mongodb.org/v3.0/reference/method/Bulk.find.upsert/

Thanks for the great work on this plugin!

**Comment by mikowals** [comment]
I don't think implementing batchUpsert in a performant way will be straight forward.  Meteor always creates its own _id for insert so a batchUpsert would require an initial check of the db to find out which docs need to be created with new _ids.  I think that initial `find` would need to be done in a loop since the document fields can be anything and are not required to be the same across documents.  For example is there a query that could return all the existing docs if I tried to upsert with `[{ firstName: "tom", age: 20}, {lastName: "Smith", height: 180}]`?  

So I think the best implementation of upsert would loop all the docs which can be done in a few lines of code without a package.  The `batchInsert` provided by this package could also be implemented with such a loop but gets a huge performance boost avoiding the loop and multiple db calls by using MongoDBs support for inserting multiple docs.
